---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted

  tasks:
    - name: Determine package manager
      ansible.builtin.set_fact:
        pkg_mgr: "{{ 'dnf' if ansible_os_family == 'RedHat' else 'apt' }}"

    - name: Ensure python3 is installed (RedHat-based)
      become: true
      ansible.builtin.dnf:
        name: python3-dnf
        state: present
      when: pkg_mgr == 'dnf'

    - name: Ensure python3 is installed (Debian-based)
      become: true
      ansible.builtin.apt:
        name: python3-apt
        state: present
      when: pkg_mgr == 'apt'

    - name: Add Clickhouse repository (RedHat-based)
      become: true
      ansible.builtin.yum_repository:
        name: clickhouse
        description: ClickHouse Repository
        baseurl: https://packages.clickhouse.com/rpm/stable/
        gpgkey: https://packages.clickhouse.com/rpm/stable/repodata/repomd.xml.key
        gpgcheck: false
        repo_gpgcheck: false
        enabled: true
      when: pkg_mgr == 'dnf'

    - name: Download Clickhouse packages (Debian-based)
      block:
        - name: Get clickhouse client package
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/stable/main/clickhouse-client_{{ clickhouse_version }}_all.deb"
            dest: "/tmp/clickhouse-client_{{ clickhouse_version }}_all.deb"
            mode: '0644'
          when: pkg_mgr == 'apt'

        - name: Get clickhouse common package
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/stable/main/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
            dest: "/tmp/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
            mode: '0644'
          when: pkg_mgr == 'apt'

        - name: Get clickhouse server package
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/stable/main/clickhouse-server_{{ clickhouse_version }}_all.deb"
            dest: "/tmp/clickhouse-server_{{ clickhouse_version }}_all.deb"
            mode: '0644'
          when: pkg_mgr == 'apt'

    - name: Install clickhouse packages (RedHat-based)
      become: true
      ansible.builtin.dnf:
        name:
          - /tmp/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm
          - /tmp/clickhouse-client-{{ clickhouse_version }}.noarch.rpm
          - /tmp/clickhouse-server-{{ clickhouse_version }}.noarch.rpm
        state: present
        disable_gpg_check: true
      notify: Start clickhouse service
      when: pkg_mgr == 'dnf'

    - name: Install clickhouse packages (Debian-based)
      become: true
      ansible.builtin.command:
        cmd: "dpkg -i /tmp/{{ item }}"
      loop:
        - clickhouse-common-static_{{ clickhouse_version }}_amd64.deb
        - clickhouse-client_{{ clickhouse_version }}_all.deb
        - clickhouse-server_{{ clickhouse_version }}_all.deb
      notify: Start clickhouse service
      when: pkg_mgr == 'apt'
      changed_when: false

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Create database
      ansible.builtin.command:
        cmd: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0

- name: Install and configure Vector
  hosts: vector
  handlers:
    - name: Restart vector service
      become: true
      ansible.builtin.systemd:
        name: vector
        state: restarted

  tasks:
    - name: Determine package manager
      ansible.builtin.set_fact:
        pkg_mgr: "{{ 'dnf' if ansible_os_family == 'RedHat' else 'apt' }}"

    - name: Create installation directory
      become: true
      ansible.builtin.file:
        path: "{{ vector_install_path }}"
        state: directory
        mode: '0755'

    - name: Get Vector distrib (RedHat-based)
      become: true
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
        dest: "/tmp/vector-{{ vector_version }}-1.x86_64.rpm"
        mode: '0644'
      when: pkg_mgr == 'dnf'

    - name: Get Vector distrib (Debian-based)
      become: true
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
        dest: "/tmp/vector_{{ vector_version }}-1_amd64.deb"
        mode: '0644'
      when: pkg_mgr == 'apt'

    - name: Install Vector package (RedHat-based)
      become: true
      ansible.builtin.dnf:
        name: "/tmp/vector-{{ vector_version }}-1.x86_64.rpm"
        state: present
      notify: Restart vector service
      when: pkg_mgr == 'dnf'

    - name: Install Vector package (Debian-based)
      become: true
      ansible.builtin.apt:
        deb: "/tmp/vector_{{ vector_version }}-1_amd64.deb"
      notify: Restart vector service
      when: pkg_mgr == 'apt'

    - name: Create configuration directory
      become: true
      ansible.builtin.file:
        path: "{{ vector_config_path }}"
        state: directory
        mode: '0755'

    - name: Deploy Vector configuration
      become: true
      ansible.builtin.template:
        src: "templates/vector_config.j2"
        dest: "{{ vector_config_path }}/vector.toml"
        mode: '0644'
      notify: Restart vector service
